validationQuery=SELECT 1

jdbc_url=jdbc:mysql://127.0.0.1:3306/cl806133279?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
jdbc_username=root
jdbc_password=123456

#jdbc_url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=cl806133279
#jdbc_username=sa
#jdbc_password=123456

